export const districtsData: Record<string, string[]> = {
  KL: ["Thiruvananthapuram","Kollam","Pathanamthitta","Alappuzha","Kottayam","Idukki","Ernakulam","Thrissur","Palakkad","Malappuram","Kozhikode","Wayanad","Kannur","Kasaragod"],
  TN: ["Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Tirunelveli","Vellore","Erode","Thoothukudi","Dindigul","Thanjavur","Ranipet","Kanchipuram","Nagercoil","Tiruppur","Karur","Nagapattinam","Virudhunagar"],
  KA: ["Bengaluru Urban","Bengaluru Rural","Mysuru","Hubballi-Dharwad","Mangaluru","Belagavi","Kalaburagi","Ballari","Shivamogga","Tumakuru","Raichur","Bidar","Hassan","Davangere","Chikkamagaluru","Kodagu","Vijayapura"],
  MH: ["Mumbai","Pune","Nagpur","Nashik","Aurangabad","Solapur","Amravati","Kolhapur","Thane","Nanded","Satara","Ahmednagar","Latur","Dhule","Jalgaon","Chandrapur","Sangli","Ratnagiri"],
  DL: ["Central Delhi","East Delhi","New Delhi","North Delhi","North East Delhi","North West Delhi","Shahdara","South Delhi","South East Delhi","South West Delhi","West Delhi"],
  UP: ["Lucknow","Kanpur","Agra","Varanasi","Prayagraj","Meerut","Noida","Ghaziabad","Gorakhpur","Bareilly","Aligarh","Moradabad","Saharanpur","Mathura","Firozabad","Jhansi"],
  WB: ["Kolkata","Howrah","Hooghly","North 24 Parganas","South 24 Parganas","Nadia","Murshadabad","Burdwan","Birbhum","Bankura","Purulia","Darjeeling","Jalpaiguri","Malda"],
  GJ: ["Ahmedabad","Surat","Vadodara","Rajkot","Bhavnagar","Jamnagar","Gandhinagar","Junagadh","Anand","Mehsana","Morbi","Bharuch","Valsad","Navsari","Amreli","Kutch"],
  RJ: ["Jaipur","Jodhpur","Kota","Bikaner","Ajmer","Udaipur","Bharatpur","Sikar","Pali","Alwar","Nagaur","Barmer","Chittorgarh","Dausa","Dholpur"],
  AP: ["Visakhapatnam","Vijayawada","Guntur","Nellore","Kurnool","Kakinada","Tirupati","Rajahmundry","Kadapa","Anantapur","Eluru","Ongole","Machilipatnam","Chittoor","Vizianagaram"],
  TS: ["Hyderabad","Warangal","Nizamabad","Khammam","Karimnagar","Ramagundam","Mahbubnagar","Adilabad","Nalgonda","Suryapet","Siddipet","Mancherial","Jagtial","Kamareddy"],
  PB: ["Ludhiana","Amritsar","Jalandhar","Patiala","Bathinda","Mohali","Hoshiarpur","Gurdaspur","Ferozepur","Faridkot","Moga","Rupnagar","Sangrur","Barnala"],
  HR: ["Gurgaon","Faridabad","Ambala","Hisar","Rohtak","Panipat","Sonipat","Karnal","Yamunanagar","Rewari","Bhiwani","Sirsa","Kurukshetra","Jhajjar"],
  MP: ["Bhopal","Indore","Jabalpur","Gwalior","Ujjain","Sagar","Rewa","Satna","Ratlam","Singrauli","Dewas","Burhanpur","Chhindwara","Khandwa"],
  BR: ["Patna","Gaya","Bhagalpur","Muzaffarpur","Purnia","Darbhanga","Bihar Sharif","Begusarai","Katihar","Munger","Chhapra","Bettiah","Siwan","Sitamarhi"],
  OR: ["Bhubaneswar","Cuttack","Berhampur","Rourkela","Sambalpur","Puri","Balasore","Bhadrak","Baripada","Jharsuguda","Keonjhar","Koraput","Dhenkanal"],
  AS: ["Guwahati","Dibrugarh","Silchar","Jorhat","Tezpur","Nagaon","Tinsukia","Karimganj","Bongaigaon","Sivasagar","Dhubri","Goalpara","Lakhimpur","Barpeta"],
  GA: ["North Goa","South Goa"],
  JK: ["Srinagar","Jammu","Anantnag","Baramulla","Udhampur","Kathua","Rajouri","Poonch","Pulwama"],
  UK: ["Dehradun","Haridwar","Roorkee","Nainital","Haldwani","Rudrapur","Kashipur","Rishikesh","Pithoragarh","Almora"],
  HP: ["Shimla","Mandi","Solan","Dharamshala","Kullu","Kangra","Hamirpur","Una","Bilaspur","Chamba"],
  JH: ["Ranchi","Jamshedpur","Dhanbad","Bokaro","Deoghar","Hazaribagh","Giridih","Ramgarh","Dumka","Palamu"],
  CG: ["Raipur","Bilaspur","Durg","Bhilai","Korba","Rajnandgaon","Jagdalpur","Ambikapur","Raigarh","Mahasamund"],
  MN: ["Imphal East","Imphal West","Thoubal","Bishnupur","Churachandpur"],
  TR: ["West Tripura","East Tripura","South Tripura","North Tripura","Gomati","Khowai","Sepahijala","Unakoti"],
  ML: ["East Khasi Hills","West Khasi Hills","Ri Bhoi","East Jaintia Hills","East Garo Hills","West Garo Hills","South Garo Hills"],
  NL: ["Kohima","Dimapur","Mokokchung","Tuensang","Wokha","Zunheboto","Phek","Mon"],
  MZ: ["Aizawl","Lunglei","Champhai","Kolasib","Serchhip","Lawngtlai","Mamit","Saiha"],
  AR: ["Itanagar","Naharlagun","Pasighat","Tawang","Ziro","Bomdila","Along","Tezu","Roing"],
  SK: ["East Sikkim","West Sikkim","North Sikkim","South Sikkim"],
  LA: ["Leh", "Kargil"]
};

export const stateNames: Record<string, string> = {
  KL: "Kerala",
  TN: "Tamil Nadu",
  KA: "Karnataka",
  MH: "Maharashtra",
  DL: "Delhi",
  UP: "Uttar Pradesh",
  WB: "West Bengal",
  GJ: "Gujarat",
  RJ: "Rajasthan",
  AP: "Andhra Pradesh",
  TS: "Telangana",
  PB: "Punjab",
  HR: "Haryana",
  MP: "Madhya Pradesh",
  BR: "Bihar",
  OR: "Odisha",
  AS: "Assam",
  GA: "Goa",
  JK: "Jammu & Kashmir",
  UK: "Uttarakhand",
  HP: "Himachal Pradesh",
  JH: "Jharkhand",
  CG: "Chhattisgarh",
  MN: "Manipur",
  TR: "Tripura",
  ML: "Meghalaya",
  NL: "Nagaland",
  MZ: "Mizoram",
  AR: "Arunachal Pradesh",
  SK: "Sikkim",
  LA: "Ladakh"
};
